#
#server:
#  port: 8020
#spring:
#  #给项目来个名字
#  application:
#    name: rabbitmq-provider
#  #配置rabbitMq 服务器
#  rabbitmq:
#    host: www.itwf.top
#    port: 5672
#    username: *****
#    password: *****
#    #虚拟host 可以不设置,使用server默认host
#    virtual-host: JCcccHost
#    publisher-returns: true
